### PR TITLE
feature/stable-diffusion-finetune

### PR DESCRIPTION
**Pull request by maekawataiki**
*Issue #, if available:*

*Description of changes:*
Added example to run Stable Diffusion Fine-tuning Script from SageMaker JumpStart 

*Testing done:*
Runned the script in SageMaker Studio Lab

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/studio-lab-examples/blob/main/CONTRIBUTING.md) doc and adhered to the example notebook best practices
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/studio-lab-examples/blob/main/README.md)
- [x] I have confirmed secret codes are not included in the example.
- [x] I have tested my notebook(s) and ensured it runs end-to-end
- [x] I have linted my notebook(s) and code using `black-nb -l 100 {path}/{notebook-name}.ipynb`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by icoxfog417** [comment]
@maekawataiki Thank you for your great contribution! I really appreciate your work. 
We found some points that make your content more secure and understandable. Could you please check these?

* About `Amazon_JumpStart_Text_To_Image.ipynb`
  * Please mention this notebook requires AWS account and charge for AWS resources. To add the approximate cost to run the notebook will be useful for our customers.
  * Please avoid to write credential in the notebook. To navigate to use `aws configure` in the Terminal will be nice.
  * Please mention about how to make the environment.
  * The cells to install `ipywidgets`, `sagemaker` and `matplotlib` are not required because of `environment.yml`.
  * `Dropdown` caused `Error displaying widget: model not found` error in my Studio Lab environment. 
* `custom_dog_image_generator.ipynb`
  * Please mention this notebook requires AWS account and charge for AWS resources.
  * Please add the instruction to use `aws configure` in the Terminal for the credential setup.
  * Please mention about how to make the environment.
  * Please mention about required role. It may need SageMaker and S3 access. (Without S3 access, it causes 403 forbidden error).
* `env.yaml`
  * Please change the name to `environment.yml`. Because [it is the common name for conda environment](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file).
* README.md
  * Please add the description about `custom_dog_image_generator.ipynb`.

**Comment by maekawataiki** [comment]
@icoxfog417
Fixed it.
The dropdown error is caused by old version of SageMaker SDK since latest version is not available in conda yet. So installed SageMaker SDK from pip instead.

**Comment by icoxfog417** [comment]
@maekawataiki Thank you for your quick fix! I confirmed that all of the points were fixed. Thank you for your dedicated work.

I found the specific execution role name. 

`RoleName='AmazonSageMaker-ExecutionRole-20211014T154824'`

If this role only exists on your environment, it will be nice to write `<replace role name with your known ARN>` etc.

**Comment by maekawataiki** [comment]
@icoxfog417 
Thanks for pointing out. Yes, it is name specific to my environment, but I kept it since it is RoleName but not ARN and might be confusing.
I updated the script, so it is more obvious for user to replace the value with RoleName format.

**Comment by icoxfog417** [comment]
Thanks ! Nice comment. I merge your great work.

**Pull request merged**
